### ISSUE TITLE
Update TypeScript version and fix package vulnerabilities

### ISSUE THREAD

**Issue by billyzkid** [body-builder/typescript-cp#11]
Great idea for a TS-friendly hot reload utility!

I tried installing the package in my project, but it failed because of the peer dependency on an old version of TypeScript.

Also could we update the package dependencies to fix the 3 vulnerabilities it's showing when installed?

**Comment by bencergazda** [comment]
Hi, thanks! Would you be open to send a PR?

**Comment by billyzkid** [comment]
I'll give it a shot.

**Comment by billyzkid** [comment]
@bencergazda Please let me know what you think. Feel free to modify and test. I was able to install and build successfully, but not able to test the actually binary output in a real project due to my noobness with node binaries and local packages.

**Comment by billyzkid** [comment]
I was able to test it locally, and found and fixed a couple of issues caused by upgrading the dependencies. LGTM!

**Comment by bencergazda** [comment]
Thanks for your work! I will publish a new release soon!
