### ISSUE TITLE
Ignore project references with emitting disabled

### ISSUE THREAD

**Issue by nwalters512** [body-builder/typescript-cp#14]
I have a project consisting of a few project references. For one, I explicitly set `"noEmit": true` in the project's `tsconfig.json`. However, `typescript-cp` errors if a referenced project doesn't have `outDir` set. I was wondering if you'd accept a PR that would essentially skip any referenced projects that have emitting disabled? I think that would match the semantics of that option and the behavior of `tsc` itself.

**Comment by bencergazda** [comment]
Hi, thanks for the great idea, I would be happy to accept a PR with this!

**Comment by nwalters512** [comment]
@bencergazda awesome! I just opened https://github.com/body-builder/typescript-cp/pull/15.
