### ISSUE TITLE
Handle two output directories

### ISSUE THREAD

**Issue by ungarson** [body-builder/typescript-cp#4]
I have this in tsconfig
```
"main": "./lib/cjs/index.js",
"module": "./lib/esm/index.js",
```

So, I have two folders with built typescript:
`lib/cjs/` and `lib/esm/`

The first one is for when my package is used on server with commonjs' require(),
second is when it's used with import()

**Right now tscp only adds files to esm folder.**

My scripts in package.json:
```
"build": "npm run build:ts && npm run build:cjs",
"build:ts": "tsc && tscp",
"build:cjs": "tsc --module commonjs --outDir lib/cjs && tscp"
```

**Comment by bencergazda** [comment]
Could you please create a minimal example repo? I would be happy to work on this, but I would like to make sure about the exact setup.

In the meantime, as a workaround, you might create a second tsconfig, that is responsible for the commonjs folder. This can be passed to tscp.

`"build:cjs": "tsc --module commonjs --outDir lib/cjs && tscp -p tsconfig.cjs.json"`

**Comment by bencergazda** [comment]
@ungarson Just a friendly ping, to keep the ticket active. It might be also enough if you share your tsconfig.json so I can find a good solution.

**Comment by ungarson** [comment]
@bencergazda hello, I think I can't give you the example repo anymore, I switched to using some other instruments, thanks!
